---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

x-defaults:
  environment: &environment
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_REGION: ap-southeast-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key

steps:
  - name: stage artefacts (test)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-artefacts stage
    depends_on:
      - clone
    environment:
      <<: *environment
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: stage cicd (test)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-cicd stage
    depends_on:
      - clone
    environment:
      <<: *environment
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: stage dns (test)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-dns stage
    depends_on:
      - clone
    environment:
      <<: *environment
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: deploy artefacts (test)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-artefacts deploy
    depends_on:
      - stage artefacts (test)
    environment:
      <<: *environment
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: deploy cicd (test)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-cicd deploy
    depends_on:
      - stage cicd (test)
    environment:
      <<: *environment
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: deploy dns (test)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-dns deploy
    depends_on:
      - stage dns (test)
    environment:
      <<: *environment
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: stage artefacts (prod)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-artefacts stage
    depends_on:
      - stage artefacts (test)
    environment:
      <<: *environment
      ENVIRONMENT: prod
    pull: always
    when:
      event:
        - pull_request

  - name: stage cicd (prod)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-cicd stage
    depends_on:
      - stage cicd (test)
    environment:
      <<: *environment
      ENVIRONMENT: prod
    pull: always
    when:
      event:
        - pull_request

  - name: stage dns (prod)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-dns stage
    depends_on:
      - stage dns (test)
    environment:
      <<: *environment
      ENVIRONMENT: prod
    pull: always
    when:
      event:
        - pull_request

  - name: deploy artefacts (prod)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-artefacts deploy
    depends_on:
      - clone
    environment:
      <<: *environment
      ENVIRONMENT: prod
    pull: always
    when:
      branch:
        - master
      event:
        - push

  - name: deploy cicd (prod)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-cicd deploy
    depends_on:
      - clone
    environment:
      <<: *environment
      ENVIRONMENT: prod
    pull: always
    when:
      branch:
        - master
      event:
        - push

  - name: deploy dns (prod)
    image: 72636c/stratus:base
    commands:
      - stratus --name {{env:ENVIRONMENT}}-aws-bedrock-dns deploy
    depends_on:
      - clone
    environment:
      <<: *environment
      ENVIRONMENT: prod
    pull: always
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: 4cee0562d6319892266f0001228bcf5f49bfaca502fd13b63eb572b7eef4df95
