---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: stage
    image: 72636c/stratus:latest-alpine
    commands:
      - stratus stage
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    pull: always
    when:
      event:
        - pull_request

  - name: deploy
    image: 72636c/stratus:latest-alpine
    commands:
      - stratus deploy
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_REGION: ap-southeast-2
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    pull: always
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: 76192f1135de677da052a84df1fd4e981c11ef80ceb008f7d4571e4150e592a0
