---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

x-defaults:
  environment: &environment
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_REGION: ap-southeast-2
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key

steps:
  - name: stage (test)
    image: 72636c/stratus:latest-base
    commands:
      - stratus stage
    environment:
      <<: *environment
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: deploy (test)
    image: 72636c/stratus:latest-base
    commands:
      - stratus deploy
    depends_on:
      - stage (test)
    environment:
      <<: *environment
      ENVIRONMENT: test
    pull: always
    when:
      event:
        - pull_request

  - name: stage (prod)
    image: 72636c/stratus:latest-base
    commands:
      - stratus stage
    depends_on:
      - stage (test)
    environment:
      <<: *environment
      ENVIRONMENT: prod
    pull: always
    when:
      event:
        - pull_request

  - name: deploy (prod)
    image: 72636c/stratus:latest-base
    commands:
      - stratus deploy
    environment:
      <<: *environment
      ENVIRONMENT: prod
    pull: always
    when:
      branch:
        - master
      event:
        - push

---
kind: signature
hmac: ec46fface92295c2435fdc40f6e2ebfce5be2a41ac061141448d2fee999fec9f
