AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS Bedrock: Artefacts'

Parameters:
  Environment:
    AllowedValues:
      - test
      - prod
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Ref Key
              SSEAlgorithm: aws:kms
      BucketName: !Sub ${AWS::AccountId}-${AWS::Region}-${Environment}-artefacts
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Environment}/artefacts/bucket-name
      Type: String
      Value: !Ref Bucket

  Key:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub Artefacts (${Environment})
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
          - Action: kms:*
            Effect: Allow
            Principal:
              AWS: !Ref AWS::AccountId
            Resource: '*'
            Sid: Allow access for Key Administrators
        Version: '2012-10-17'

Outputs:
  BucketArn:
    Export:
      Name: !Sub ${Environment}:artefacts:bucket-arn
    Value: !GetAtt Bucket.Arn

  KeyArn:
    Export:
      Name: !Sub ${Environment}:artefacts:key-arn
    Value: !GetAtt Key.Arn
