AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS Bedrock: Artefacts'

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::AccountId}-${AWS::Region}-artefacts
      ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            KMSMasterKeyID: !Ref Key
            SSEAlgorithm: aws:kms

  BucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: artefacts/bucket-name
      Type: String
      Value: !Ref Bucket

  Key:
    Type: AWS::KMS::Key
    Properties:
      Description: Artefacts
      EnableKeyRotation: true
      KeyPolicy:
        - Action: kms:*
          Effect: Allow
          Principal:
            AWS: !Ref AWS::AccountId
          Resource: '*'
          Sid: Allow access for Key Administrators

Outputs:
  BucketArn:
    Export:
      Name: artefacts:bucket-arn
    Value: !GetAtt Bucket.Arn

  KeyArn:
    Export:
      Name: artefacts:key-arn
    Value: !GetAtt Key.Arn
