AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS Bedrock: CI/CD'

Parameters:
  Environment:
    AllowedValues:
      - test
      - prod
    Type: String

Resources:
  DroneAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Serial: 0
      Status: Active
      UserName: !Ref DroneUser

  DroneSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub /${Environment}/cicd/drone
      SecretString: !Sub '{"AccessKeyId": "${DroneAccessKey}", "SecretAccessKey": "${DroneAccessKey.SecretAccessKey}"}'

  DroneUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      UserName: !Sub ${AWS::Region}.${Environment}.cicd.drone
